apiVersion: v1
baseDomain: lab.example.com
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      zones:
      - us-east-1a
      type: m4.2xlarge
  replicas: 2
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      zones:
      - us-east-1a
      type: m4.2xlarge
  replicas: 3
metadata:
  creationTimestamp: null
  name: ocp-cluster
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"XJlbGVhc2Ub3BlbnNoaWZ0LtZGV2K21pa2VwaGl5mZXF3dW5panJksbGlwczE5NzMxaTJpOGb2F5ZHFveHRoMDcwUkNRNEY5RMGQ6TE5TQVE4U01Q1g0VDzUwT1Y0STZUNkVNXU1U3QTTUg5MEJIWFZE2RjFVRDVHUwYVUhXTjNPUz==","email":"student@workstation.lab.example.com"},"quay.io":{"auth":"XJlbGVhc2Ub3BlbnNoaWZ0LtZGV2K21pa2VwaGl5mZXF3dW5panJksbGlwczE5NzMxaTJpOGb2F5ZHFveHRoMDcwUkNRNEY5RMGQ6TE5TQVE4U01Q1g0VDzUwT1Y0STZUNkVNXU1U3QTTUg5MEJIWFZE2RjFVRDVHUwYVUhXTjNPUz==","email":"student@workstation.lab.example.com"},"registry.connect.redhat.com":{"auth":"OmV5SmhiR2NpT2lKU1V6VNTIyODExMXx1aGMtMUkyaThOZmV5SnpkV0lpT2Vxd1VuaWpyRE9hWURxb3h0SDBkXhzTURSbVlNaUo5LmlKaU56YzJZMlUtTTBNelpoT1RNMU56WmhOR00xT1RnME1tTTVPU0o5LlMyVXg3eHRIN0k5ekxvSzBQQlBTSmtpejF2R2NkSG0wNkozOS1iUlJsZ1hMMXAyXzhckFJbmN6aHBTRXRZUEtTc2Z3c0xuToTzFkaDQyMkZUWDhhGhndkUzR1A5aGphWF96X1lQTUVOZnB0Q2dHUFNwdkpaYlZPdU1Zc2VtWFdBM1dvWXZna0cyWU9MTTQyRFBuSzBHWDRTYzIwdVlGQWtvRDJBTWVIeUVUeEI4RnRNZGRJSkp0TzhCcGhhaTlJMXlKSjhnUFdiRDVLbDRRTVY0dTUzanctSkM0Q1Z5S3MwSldDd3lNUW9HMXByR3JlMFFRUU9jZ2hhUVphSlN2cUEzbDlvMjhmakpQM0FTZmtRanZIQU9WLU1mbDFZdWpHWWVaSkhyRVFWQUFULW13aXI1NWJ4ZG9iV3ViM1U2dm5nWjVlNWJndGZJS2ZURVdDOEJvN3J3UkJzSC1xUnRfZnA0WHllZldBUklfbWF1QjMwRmxvZU9zV0FBeU9TMEQ3UjBXYmRTMU1JX04yNDVHMlJiUTA2ampRaTBLSi1laTc1Q29ZMVpSOUNrcW1rNG1GdmxFREdjalhEMHFhNkZqN3VxTXFNa3ZHSFlZWWtJcWdaVkZlaGNBTXJOdnJTcEJyeXQ2VnBteDRnZ2wwd3hiQ1BONHNzdHpDMlJsazh0ejY4Ym9iano3YlZrQUpJb3VJMFZyNnVIQ09vLVp6S0RvOGVwUGE5S3U0aEVTSWNjUWFkLURzTlhWjBwWnVxbGF5NnFaNEwwSUxHb1BPLXIzZFpyNWoS1F0UGNyclhxbEh2SUkzS3ZRNjRkbjNWLUpIdXlZTHdPbnByVlhYS1VqbDRDOFZTlpOalV5MFktZHb0k2dlFrbUtmTG9mVo1aTdJVkZXgwclVwc3hCeC1j","email":"student@workstation.lab.example.com"},"registry.redhat.io":{"auth":"OmV5SmhiR2NpT2lKU1V6VNTIyODExMXx1aGMtMUkyaThOZmV5SnpkV0lpT2Vxd1VuaWpyRE9hWURxb3h0SDBkXhzTURSbVlNaUo5LmlKaU56YzJZMlUtTTBNelpoT1RNMU56WmhOR00xT1RnME1tTTVPU0o5LlMyVXg3eHRIN0k5ekxvSzBQQlBTSmtpejF2R2NkSG0wNkozOS1iUlJsZ1hMMXAyXzhckFJbmN6aHBTRXRZUEtTc2Z3c0xuToTzFkaDQyMkZUWDhhGhndkUzR1A5aGphWF96X1lQTUVOZnB0Q2dHUFNwdkpaYlZPdU1Zc2VtWFdBM1dvWXZna0cyWU9MTTQyRFBuSzBHWDRTYzIwdVlGQWtvRDJBTWVIeUVUeEI4RnRNZGRJSkp0TzhCcGhhaTlJMXlKSjhnUFdiRDVLbDRRTVY0dTUzanctSkM0Q1Z5S3MwSldDd3lNUW9HMXByR3JlMFFRUU9jZ2hhUVphSlN2cUEzbDlvMjhmakpQM0FTZmtRanZIQU9WLU1mbDFZdWpHWWVaSkhyRVFWQUFULW13aXI1NWJ4ZG9iV3ViM1U2dm5nWjVlNWJndGZJS2ZURVdDOEJvN3J3UkJzSC1xUnRfZnA0WHllZldBUklfbWF1QjMwRmxvZU9zV0FBeU9TMEQ3UjBXYmRTMU1JX04yNDVHMlJiUTA2ampRaTBLSi1laTc1Q29ZMVpSOUNrcW1rNG1GdmxFREdjalhEMHFhNkZqN3VxTXFNa3ZHSFlZWWtJcWdaVkZlaGNBTXJOdnJTcEJyeXQ2VnBteDRnZ2wwd3hiQ1BONHNzdHpDMlJsazh0ejY4Ym9iano3YlZrQUpJb3VJMFZyNnVIQ09vLVp6S0RvOGVwUGE5S3U0aEVTSWNjUWFkLURzTlhWjBwWnVxbGF5NnFaNEwwSUxHb1BPLXIzZFpyNWoS1F0UGNyclhxbEh2SUkzS3ZRNjRkbjNWLUpIdXlZTHdPbnByVlhYS1VqbDRDOFZTlpOalV5MFktZHb0k2dlFrbUtmTG9mVo1aTdJVkZXgwclVwc3hCeC1j","email":"student@workstation.lab.example.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDIIDIgGavOV/+G9z8lCLc4u1dMVGL5q3d9PN+MAOFu8HJwBfolcoOf5FBBeNHJOHmtZTVuJw+Xx7ByOHnzTSwissuRsmQyUlyXoTCdoPbo7zPqj4vfx/lLnI/8rFYOw0P+zzvOeSTvYSVYyvYbmxGC/ZDT+LCo8bgHyncTkMk7irAMuQc/Q52sqie/rIFVMFfKVWCTlVm72yNw73dz3dL7nAqorl8NbTx0xmgKgbFNN0Gi9qo4UpZ5SzugjhC4RJxl2vyNnARTTqnHXsj+j2KHOin9Tz5sn625a6yuR2q2Rd5eD7HLMRKeMxw+3WMHeWPpJeHt71BKQfLgDYGwEZjVTovuJcrAPsmbmz/xkgjZOT1WZ+X4t3rVUNbWinQmEmSrEfWb0xf19CMsXZhKx3RuEdeqZ50w2YzoMr/8T/rOoDUDXCBTZ390LdK9iDyQJX7Xsu+xxLi/vA10ZqRznWVslzJFs9IVq/kKzUfJBf0gNGlrLE68E/8d0Ul70oCORHpXeUI6BCf4djIL716jdHr8x5+thSQKr+UhShQ+OB1F9OSXDxBnm9mldwL8k/BFwM2wq5iARAOf6PB1AE0ubun4iMTK+IUDMtWE+q2H1f0bCrg3YA5vMsHGIdjpJnB4DciuPIhbiTBBkXQzvccTvKsxGNyW3gdpxPi3xXFqqitgAw== Openshift Cluster Key
